### ISSUE TITLE
running todo

### ISSUE THREAD

**Issue by itsjoekent** [deadlybutter/ld39#1]
### PARTICLES
- [x] cell explosions either on death or cell-cell collision
- [x] particle explosions when protons collide with cells 

### GAMEPLAY
- [x] prevent double highlight
- [ ] pop-up bonus cells (3-5?)
- [ ] sound
- [ ] instructions to place cells at spawn, and a quick countdown after before game starts
- [ ] determine when game is over
- [ ] AI Logic

### NICE TO HAVES
- [ ] Main menu
- [ ] Demo / Tutorial

**Comment by itsjoekent** [comment]
- put instructions w/ HTML below
- countdown type thing for sure
- play button

- game over logic
- AI Logic

- bonuses if im really feeling it
